---
title: "Mapas ENSANUT 2018"
author:
- Diego López Tamayo ^[El Colegio de México, diego.lopez@colmex.mx]
output:
  pdf_document:
    toc: yes
    toc_depth: '3'
  html_document:
    df_print: paged
    highlight: tango
    theme: simplex
    toc: yes
    toc_depth: 3
    toc_float: yes
header:
- \usepackage{amsmath}
- \usepackage[spanish]{babel}
- \selectlanguage{spanish}
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Directorio y librerías

```{r}
#Directorio de trabajo
setwd("~/Documents/GitHub/ensanut_mun")
```

```{r}
# Configuración
rm(list = ls())
# Librerías
pacman::p_load(tidyverse,
               ggplot2,
               shiny,
               gmodels,
               tmap,
               leaflet,
               foreign,
               expss,
               fishualize)
```

```{r}
#Paqueterías para mapear
library(sf)
#install.packages("ggspatial")
library("ggspatial")
theme_set(theme_bw())
library("colorspace")
# hcl_palettes(plot = TRUE)
p_load(rstudioapi, lintr, raster, viridis, cowplot, rmarkdown)
# sessionInfo()
```


















